CREATE TABLE "GCG_6209_BI_ORD_INFO" (
 "ORDER_NO" CHAR(10),
 "CUSTOMER_NO" CHAR(10),
 "CUSTOMER_NAME" CHAR(30),
 "COMP_NAME" CHAR(30),
 "COMP_PHONE" CHAR(50),
 "USER_NO" CHAR(8),
 "TERMINAL_NO" CHAR(3),
 "BI_RUN_ID" LONGVARCHAR,
 "REPT_ID" INTEGER );